version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 6688:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress_user
      WORDPRESS_DB_PASSWORD: 123456
      WORDPRESS_DB_NAME: wordpress
      container_name: wordpress
    networks:
      - wp
  db:
    image: mysql:5.7
    restart: always
    container_name: db
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress_user
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: 123456
    networks:
      - wp
networks:
  wp: